# Generated by Django 4.2.24 on 2025-10-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epayco_ref', models.CharField(help_text='Referencia única de la transacción en ePayco', max_length=255, unique=True, verbose_name='Referencia ePayco')),
                ('epayco_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Transacción ePayco')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('payment_method', models.CharField(choices=[('card', 'Tarjeta de Crédito/Débito'), ('pse', 'PSE'), ('cash', 'Efectivo'), ('transfer', 'Transferencia')], max_length=20, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado del Pago')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de ePayco', verbose_name='Datos de Respuesta')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='sales.order', verbose_name='Pedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
