# Generated by Django 4.2.24 on 2025-10-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='epayco_ref',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='epayco_transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, help_text='Referencia externa única del pago', max_length=255, null=True, verbose_name='Referencia Externa'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mercadopago_id',
            field=models.CharField(blank=True, help_text='ID único de la transacción en MercadoPago', max_length=255, null=True, unique=True, verbose_name='ID MercadoPago'),
        ),
        migrations.AddField(
            model_name='payment',
            name='preference_id',
            field=models.CharField(blank=True, help_text='ID de la preferencia de pago creada', max_length=255, null=True, verbose_name='ID de Preferencia'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('pse', 'PSE'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('cash', 'Efectivo'), ('bank_transfer', 'Transferencia Bancaria')], max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Respuesta completa de MercadoPago', verbose_name='Datos de Respuesta'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('in_process', 'En Proceso'), ('in_mediation', 'En Mediación')], default='pending', max_length=20, verbose_name='Estado del Pago'),
        ),
    ]
