# Generated by Django 4.2.24 on 2025-09-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('caducado', 'Caducado')], default='disponible', max_length=20)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.crop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
