# Generated by Django 4.2.24 on 2025-09-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('precio_por_unidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Unidad')),
                ('cantidad_disponible', models.PositiveIntegerField(verbose_name='Cantidad Disponible')),
                ('cantidad_minima', models.PositiveIntegerField(default=1, verbose_name='Cantidad Mínima de Venta')),
                ('departamento', models.CharField(default='', max_length=100, verbose_name='Departamento de Origen')),
                ('ciudad', models.CharField(default='', max_length=100, verbose_name='Ciudad/Municipio de Origen')),
                ('categoria', models.CharField(choices=[('Frutas', 'Frutas'), ('Verduras', 'Verduras'), ('Hortalizas', 'Hortalizas'), ('Granos', 'Granos'), ('Tubérculos', 'Tubérculos'), ('Hierbas', 'Hierbas y Especias'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Agotada', 'Agotada')], default='Activa', max_length=10, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción Adicional')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='Imagen del Producto')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='inventory.crop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
