# Generated by Django 4.2.24 on 2025-09-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('precio_por_unidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Unidad ($)')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Disponible')),
                ('cantidad_minima', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad Mínima de Pedido')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('pausado', 'Pausado'), ('agotado', 'Agotado')], default='disponible', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, help_text='Describe la calidad, características especiales, etc.', null=True, verbose_name='Descripción')),
                ('cultivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicacion', to='inventory.crop', verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
