# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_add_finca_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='unidad_medida',
            field=models.CharField(
                choices=[
                    ('kg', 'Kilogramos (kg)'),
                    ('g', 'Gramos (g)'),
                    ('libras', 'Libras (lb)'),
                    ('arrobas', 'Arrobas (@)'),
                    ('toneladas', 'Toneladas (t)'),
                    ('unidades', 'Unidades (fijo)'),
                    ('cajas', 'Cajas (fijo)'),
                    ('bultos', 'Bultos/Sacos (fijo)'),
                ],
                default='kg',
                max_length=20,
                verbose_name='Unidad de Medida',
            ),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cantidad_minima',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad Mínima de Venta'),
        ),
    ]

