# Generated by Django 4.2.24 on 2025-09-30 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_crop_imagen_alter_crop_fecha_disponibilidad'),
        ('marketplace', '0002_publication_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.AddField(
            model_name='publication',
            name='categoria',
            field=models.CharField(choices=[('Frutas', 'Frutas'), ('Verduras', 'Verduras'), ('Hortalizas', 'Hortalizas'), ('Granos', 'Granos'), ('Tubérculos', 'Tubérculos'), ('Hierbas', 'Hierbas y Especias'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='publication',
            name='ciudad',
            field=models.CharField(default='', max_length=100, verbose_name='Ciudad/Municipio de Origen'),
        ),
        migrations.AddField(
            model_name='publication',
            name='departamento',
            field=models.CharField(default='', max_length=100, verbose_name='Departamento de Origen'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cantidad_minima',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Mínima de Venta'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='inventory.crop'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción Adicional'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Agotada', 'Agotada')], default='Activa', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='precio_por_unidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Unidad'),
        ),
    ]
