# Generated by Django 4.2.24 on 2025-10-31 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_grams_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('libras', 'Libras (lb)'), ('arrobas', 'Arrobas (@)'), ('toneladas', 'Toneladas (t)'), ('unidades', 'Unidades (fijo)'), ('cajas', 'Cajas (fijo)'), ('bultos', 'Bultos/Sacos (fijo)')], default='kg', max_length=20, verbose_name='Unidad de Medida'),
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='publications/', verbose_name='Imagen')),
                ('is_primary', models.BooleanField(default=False, help_text='Marca esta imagen como la principal para mostrar en el marketplace', verbose_name='Imagen Principal')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización en el carrusel', verbose_name='Orden')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.publication', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Imagen de Publicación',
                'verbose_name_plural': 'Imágenes de Publicación',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['publication', 'order'], name='marketplace_publica_f3cac4_idx'), models.Index(fields=['publication', 'is_primary'], name='marketplace_publica_b0ad11_idx')],
            },
        ),
    ]
