# Generated by Django 4.2.24 on 2025-09-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='fecha_primera_compra',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Primera Compra'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='gastos_totales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos Totales'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='total_compras',
            field=models.IntegerField(default=0, verbose_name='Total de Compras'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Calificación Promedio como Vendedor'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='fecha_primera_venta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Primera Venta'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='ingresos_totales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos Totales'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='total_calificaciones',
            field=models.IntegerField(default=0, verbose_name='Total de Calificaciones Recibidas'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='total_ventas',
            field=models.IntegerField(default=0, verbose_name='Total de Ventas'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tipo de Negocio'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='farm_description',
            field=models.TextField(blank=True, verbose_name='Descripción de la Finca'),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='main_crops',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cultivos Principales'),
        ),
    ]
