# Generated by Django 4.2.24 on 2025-10-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_sell',
            field=models.BooleanField(default=False, help_text='Indica si el usuario puede crear publicaciones y vender productos', verbose_name='¿Puede vender?'),
        ),
    ]
