# Generated by Django 4.2.24 on 2025-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_can_sell_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Negocio'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad/Municipio'),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad/Municipio'),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='direccion',
            field=models.CharField(blank=True, help_text='Ej: Vereda, finca, sector específico', max_length=255, null=True, verbose_name='Dirección específica'),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Campo legacy - se actualizará automáticamente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='farm_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la Finca'),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='main_crops',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cultivos Principales'),
        ),
    ]
