# Generated by Django 4.2.24 on 2025-09-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_buyerprofile_fecha_primera_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Imagen de Perfil'),
        ),
    ]
