# Generated by Django 4.2.24 on 2025-10-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de cédula de identidad', max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
