# Generated by Django 4.2.24 on 2025-10-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_buyerprofile_nullable'),
    ]

    operations = [
        # Usar SQL directo para asegurar que los campos sean nullable
        migrations.RunSQL(
            # Forward SQL - hacer los campos nullable
            sql=[
                'ALTER TABLE accounts_buyerprofile ALTER COLUMN company_name DROP NOT NULL;',
                'ALTER TABLE accounts_buyerprofile ALTER COLUMN business_type DROP NOT NULL;',
                'ALTER TABLE accounts_buyerprofile ALTER COLUMN departamento DROP NOT NULL;',
                'ALTER TABLE accounts_buyerprofile ALTER COLUMN ciudad DROP NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN departamento DROP NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN ciudad DROP NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN direccion DROP NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN location DROP NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN farm_description DROP NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN main_crops DROP NOT NULL;',
            ],
            # Reverse SQL - hacer los campos NOT NULL de nuevo (para rollback)
            reverse_sql=[
                'ALTER TABLE accounts_buyerprofile ALTER COLUMN company_name SET NOT NULL;',
                'ALTER TABLE accounts_buyerprofile ALTER COLUMN business_type SET NOT NULL;',
                'ALTER TABLE accounts_buyerprofile ALTER COLUMN departamento SET NOT NULL;',
                'ALTER TABLE accounts_buyerprofile ALTER COLUMN ciudad SET NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN departamento SET NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN ciudad SET NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN direccion SET NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN location SET NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN farm_description SET NOT NULL;',
                'ALTER TABLE accounts_producerprofile ALTER COLUMN main_crops SET NOT NULL;',
            ],
        ),
    ]