# Generated by Django 4.2.24 on 2025-10-05 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fix_nullable_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Finca')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad/Municipio')),
                ('direccion', models.CharField(blank=True, help_text='Vereda, sector o dirección específica', max_length=255, null=True, verbose_name='Dirección/Vereda')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la finca, tipo de terreno, etc.', null=True, verbose_name='Descripción')),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='Área total de la finca en hectáreas', max_digits=10, null=True, verbose_name='Área (hectáreas)')),
                ('cultivos_principales', models.CharField(blank=True, help_text='Principales cultivos de esta finca', max_length=255, null=True, verbose_name='Cultivos Principales')),
                ('activa', models.BooleanField(default=True, verbose_name='Finca Activa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'nombre')},
            },
        ),
    ]
