# Generated by Django 4.2.24 on 2025-10-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
