# Generated by Django 4.2.24 on 2025-10-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_ciudad_user_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_password',
            field=models.BooleanField(default=True, help_text='Indica si el usuario tiene una contraseña configurada', verbose_name='Tiene contraseña'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=False, help_text='Indica si el usuario se registró con Google', verbose_name='Usuario de Google'),
        ),
    ]
