# Generated by Django 4.2.24 on 2025-10-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_has_password_user_is_google_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Productor', 'Productor'), ('Comprador', 'Comprador')], max_length=10, null=True),
        ),
    ]
