# Generated by Django 4.2.24 on 2025-10-23 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('login', 'Inicio de sesión'), ('logout', 'Cerrar sesión'), ('view', 'Ver'), ('export', 'Exportar'), ('import', 'Importar')], max_length=20, verbose_name='Tipo de Acción')),
                ('object_type', models.CharField(choices=[('user', 'Usuario'), ('crop', 'Cultivo'), ('publication', 'Publicación'), ('order', 'Pedido'), ('farm', 'Finca'), ('system', 'Sistema')], max_length=20, verbose_name='Tipo de Objeto')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('object_name', models.CharField(max_length=255, verbose_name='Nombre del Objeto')),
                ('description', models.TextField(help_text='Detalles de la acción realizada', verbose_name='Descripción')),
                ('changes', models.JSONField(blank=True, help_text='Cambios específicos realizados (JSON)', null=True, verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Acción de Administrador',
                'verbose_name_plural': 'Acciones de Administrador',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'created_at'], name='accounts_ad_admin_i_94d728_idx'), models.Index(fields=['action_type', 'created_at'], name='accounts_ad_action__9c81d8_idx'), models.Index(fields=['object_type', 'created_at'], name='accounts_ad_object__6a7524_idx')],
            },
        ),
    ]
