# Generated by Django 4.2.24 on 2025-10-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_adminaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de cédula de identidad', max_length=20, null=True, verbose_name='Cédula'),
        ),
    ]
