# Generated by Django 4.2.24 on 2025-10-24 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_make_cedula_non_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=6, verbose_name='Código de Recuperación')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_used', models.BooleanField(default=False, verbose_name='Código Usado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Código de Recuperación',
                'verbose_name_plural': 'Códigos de Recuperación',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_used'], name='accounts_pa_code_41ca5e_idx'), models.Index(fields=['email', 'is_used'], name='accounts_pa_email_c4ebc1_idx'), models.Index(fields=['expires_at'], name='accounts_pa_expires_d44861_idx')],
            },
        ),
    ]
