# Generated by Django 4.2.24 on 2025-10-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cultivo')),
                ('categoria', models.CharField(choices=[('hortalizas', 'Hortalizas'), ('frutas', 'Frutas'), ('cereales_granos', 'Cereales y Granos'), ('leguminosas', 'Leguminosas'), ('tuberculos', 'Tubérculos'), ('hierbas_aromaticas', 'Hierbas Aromáticas'), ('otros', 'Otros')], default='otros', max_length=30, verbose_name='Categoría')),
                ('cantidad_estimada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Estimada')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('toneladas', 'Toneladas'), ('libras', 'Libras'), ('unidades', 'Unidades'), ('cajas', 'Cajas'), ('bultos', 'Bultos'), ('arrobas', 'Arrobas')], default='kg', max_length=20, verbose_name='Unidad de Medida')),
                ('estado', models.CharField(choices=[('sembrado', 'Sembrado'), ('en_crecimiento', 'En Crecimiento'), ('listo_para_cosechar', 'Listo para Cosecha'), ('cosechado', 'Cosechado')], default='sembrado', max_length=20, verbose_name='Estado del Cultivo')),
                ('fecha_disponibilidad', models.DateField(blank=True, null=True, verbose_name='Disponible Desde')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='Imagen del Cultivo')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre el cultivo', null=True, verbose_name='Notas Adicionales')),
                ('productor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to=settings.AUTH_USER_MODEL, verbose_name='Productor')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['-created_at'],
            },
        ),
    ]
