# Generated by Django 5.2.6 on 2025-09-29 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Producto')),
                ('categoria', models.CharField(choices=[('hortalizas', 'Hortalizas'), ('frutas', 'Frutas'), ('cereales_granos', 'Cereales y Granos'), ('leguminosas', 'Leguminosas'), ('tuberculos', 'Tubérculos'), ('hierbas_aromaticas', 'Hierbas Aromáticas'), ('otros', 'Otros')], default='otros', max_length=30, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_producto', models.CharField(help_text='Ej: Tomate, Lechuga, Zanahoria, etc.', max_length=100, verbose_name='Nombre del Producto')),
                ('categoria', models.CharField(choices=[('hortalizas', 'Hortalizas'), ('frutas', 'Frutas'), ('cereales_granos', 'Cereales y Granos'), ('leguminosas', 'Leguminosas'), ('tuberculos', 'Tubérculos'), ('hierbas_aromaticas', 'Hierbas Aromáticas'), ('otros', 'Otros')], default='otros', max_length=30, verbose_name='Categoría')),
                ('departamento', models.CharField(blank=True, help_text='Departamento donde se encuentra este cultivo', max_length=100, verbose_name='Departamento')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad donde se encuentra este cultivo', max_length=100, verbose_name='Ciudad/Municipio')),
                ('cantidad_estimada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Estimada')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('toneladas', 'Toneladas'), ('libras', 'Libras'), ('unidades', 'Unidades'), ('cajas', 'Cajas'), ('bultos', 'Bultos'), ('arrobas', 'Arrobas')], max_length=20, verbose_name='Unidad de Medida')),
                ('estado', models.CharField(choices=[('sembrado', 'Sembrado'), ('en_crecimiento', 'En Crecimiento'), ('listo_cosecha', 'Listo para Cosecha'), ('cosechado', 'Cosechado')], max_length=20, verbose_name='Estado del Cultivo')),
                ('fecha_disponibilidad', models.DateField(verbose_name='Fecha Estimada de Disponibilidad')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre el cultivo', null=True, verbose_name='Notas Adicionales')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to=settings.AUTH_USER_MODEL, verbose_name='Productor')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['-created_at'],
            },
        ),
    ]
