# Generated by Django 4.2.24 on 2025-09-29 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='nombre_producto',
        ),
        migrations.AddField(
            model_name='crop',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='inventory.product', verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='cantidad_estimada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Estimada'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='estado',
            field=models.CharField(choices=[('sembrado', 'Sembrado'), ('en_crecimiento', 'En Crecimiento'), ('listo_cosecha', 'Listo para Cosecha'), ('cosechado', 'Cosechado')], default='sembrado', max_length=20, verbose_name='Estado del Cultivo'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fecha_disponibilidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='productor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to=settings.AUTH_USER_MODEL, verbose_name='Productor'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('toneladas', 'Toneladas'), ('libras', 'Libras'), ('unidades', 'Unidades'), ('cajas', 'Cajas'), ('bultos', 'Bultos'), ('arrobas', 'Arrobas')], default='kg', max_length=20, verbose_name='Unidad de Medida'),
        ),
    ]
