# Generated by Django 4.2.24 on 2025-09-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(choices=[('hortalizas', 'Hortalizas'), ('frutas', 'Frutas'), ('cereales_granos', 'Cereales y Granos'), ('leguminosas', 'Leguminosas'), ('tuberculos', 'Tubérculos'), ('hierbas_aromaticas', 'Hierbas Aromáticas'), ('otros', 'Otros')], default='otros', max_length=30, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
