# Generated by Django 4.2.24 on 2025-10-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_farm'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='finca',
            field=models.ForeignKey(blank=True, help_text='Finca donde se cultiva este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivos', to='accounts.farm', verbose_name='Finca'),
        ),
    ]
