# Generated by Django 4.2.24 on 2025-09-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_product_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='categoria',
            field=models.CharField(choices=[('hortalizas', 'Hortalizas'), ('frutas', 'Frutas'), ('cereales_granos', 'Cereales y Granos'), ('leguminosas', 'Leguminosas'), ('tuberculos', 'Tubérculos'), ('hierbas_aromaticas', 'Hierbas Aromáticas'), ('otros', 'Otros')], default='otros', max_length=30, verbose_name='Categoría'),
        ),
    ]
