# Generated by Django 4.2.24 on 2025-09-29 22:14

from django.db import migrations

def set_default_product(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Crop = apps.get_model('inventory', 'Crop')
    
    # Get or create the default product
    default_product, created = Product.objects.get_or_create(
        nombre='Producto no especificado',
        defaults={'categoria': 'otros'}
    )
    
    # Update all crops that have no product
    Crop.objects.filter(producto__isnull=True).update(producto=default_product)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_crop_categoria_remove_crop_ciudad_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_product),
    ]
