# Generated by Django 4.2.24 on 2025-09-30 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20250929_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='inventory.product', verbose_name='Tipo de Producto'),
        ),
    ]
