# Generated by Django 4.2.24 on 2025-09-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_crop_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad donde se encuentra este cultivo', max_length=100, verbose_name='Ciudad/Municipio'),
        ),
        migrations.AddField(
            model_name='crop',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento donde se encuentra este cultivo', max_length=100, verbose_name='Departamento'),
        ),
    ]
