# Generated by Django 4.2.24 on 2025-09-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_crop_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='Imagen del Cultivo'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fecha_disponibilidad',
            field=models.DateField(blank=True, null=True, verbose_name='Disponible Desde'),
        ),
    ]
