# Generated by Django 4.2.24 on 2025-10-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_crop_finca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='imagen',
        ),
    ]
