# Generated by Django 4.2.24 on 2025-10-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farm'),
        ('inventory', '0005_remove_crop_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='finca',
            field=models.ForeignKey(blank=True, help_text='Finca donde se cultiva este producto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='core.farm', verbose_name='Finca'),
        ),
    ]
