# Generated by Django 4.2.24 on 2025-10-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_crop_finca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='notas',
            field=models.TextField(blank=True, help_text='Información adicional, observaciones o comentarios sobre el cultivo', null=True, verbose_name='Notas Adicionales'),
        ),
    ]
