# Generated by Django 4.2.24 on 2025-10-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_crop_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Adicionales'),
        ),
    ]
