# Generated by Django 5.2.6 on 2025-09-29 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='marketplace.publication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sales.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_acordada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Acordada')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado por Vendedor'), ('en_preparacion', 'En Preparación'), ('enviado', 'Enviado'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('recibido', 'Recibido por Comprador'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Pedido')),
                ('notas_comprador', models.TextField(blank=True, null=True, verbose_name='Notas del Comprador')),
                ('notas_vendedor', models.TextField(blank=True, null=True, verbose_name='Notas del Vendedor')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de Entrega')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_como_comprador', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='marketplace.publication', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_ventas', models.IntegerField(default=0, verbose_name='Total de Ventas')),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos Totales')),
                ('total_compras', models.IntegerField(default=0, verbose_name='Total de Compras')),
                ('gastos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos Totales')),
                ('calificacion_promedio_como_vendedor', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Calificación Promedio como Vendedor')),
                ('calificacion_promedio_como_comprador', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Calificación Promedio como Comprador')),
                ('total_calificaciones_como_vendedor', models.IntegerField(default=0)),
                ('total_calificaciones_como_comprador', models.IntegerField(default=0)),
                ('fecha_primera_venta', models.DateTimeField(blank=True, null=True)),
                ('fecha_primera_compra', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_stats', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('comprador_a_vendedor', 'Comprador califica a Vendedor'), ('vendedor_a_comprador', 'Vendedor califica a Comprador')], max_length=25, verbose_name='Tipo de Calificación')),
                ('calificacion_general', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación General')),
                ('calificacion_comunicacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Comunicación')),
                ('calificacion_puntualidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntualidad')),
                ('calificacion_calidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calidad del Producto/Servicio')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('recomendaria', models.BooleanField(default=True, verbose_name='¿Recomendarías a este usuario?')),
                ('calificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Calificado')),
                ('calificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL, verbose_name='Calificador')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='sales.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-created_at'],
                'unique_together': {('pedido', 'calificador')},
            },
        ),
    ]
