# Generated by Django 4.2.24 on 2025-09-27 23:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AddField(
            model_name='order',
            name='fecha_entrega_estimada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada'),
        ),
        migrations.AddField(
            model_name='order',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AddField(
            model_name='order',
            name='notas_vendedor',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Vendedor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado por Vendedor'), ('en_preparacion', 'En Preparación'), ('enviado', 'Enviado'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('recibido', 'Recibido por Comprador'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Pedido'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_ventas', models.IntegerField(default=0, verbose_name='Total de Ventas')),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos Totales')),
                ('total_compras', models.IntegerField(default=0, verbose_name='Total de Compras')),
                ('gastos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos Totales')),
                ('calificacion_promedio_como_vendedor', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Calificación Promedio como Vendedor')),
                ('calificacion_promedio_como_comprador', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Calificación Promedio como Comprador')),
                ('total_calificaciones_como_vendedor', models.IntegerField(default=0)),
                ('total_calificaciones_como_comprador', models.IntegerField(default=0)),
                ('fecha_primera_venta', models.DateTimeField(blank=True, null=True)),
                ('fecha_primera_compra', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_stats', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('comprador_a_vendedor', 'Comprador califica a Vendedor'), ('vendedor_a_comprador', 'Vendedor califica a Comprador')], max_length=25, verbose_name='Tipo de Calificación')),
                ('calificacion_general', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación General')),
                ('calificacion_comunicacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Comunicación')),
                ('calificacion_puntualidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntualidad')),
                ('calificacion_calidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calidad del Producto/Servicio')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('recomendaria', models.BooleanField(default=True, verbose_name='¿Recomendarías a este usuario?')),
                ('calificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Calificado')),
                ('calificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL, verbose_name='Calificador')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='sales.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-created_at'],
                'unique_together': {('pedido', 'calificador')},
            },
        ),
    ]
