# Generated by Django 4.2.24 on 2025-09-30 03:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_publication_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='marketplace.publication'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sales.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='cantidad_acordada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Acordada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_como_comprador', to=settings.AUTH_USER_MODEL, verbose_name='Comprador'),
        ),
        migrations.AlterField(
            model_name='order',
            name='direccion_entrega',
            field=models.TextField(blank=True, verbose_name='Dirección de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='publicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='marketplace.publication', verbose_name='Publicación'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='calificacion_calidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calidad del Producto/Servicio'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='calificacion_comunicacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Comunicación'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='calificacion_general',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación General'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='calificacion_puntualidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntualidad'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='calificado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Calificado'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='calificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL, verbose_name='Calificador'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='pedido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='sales.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tipo',
            field=models.CharField(choices=[('comprador_a_vendedor', 'Comprador califica a Vendedor'), ('vendedor_a_comprador', 'Vendedor califica a Comprador')], default='comprador_a_vendedor', max_length=25, verbose_name='Tipo de Calificación'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
