# Generated by Django 4.2.24 on 2025-10-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_rating_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado por Vendedor'), ('en_preparacion', 'En Preparación'), ('enviado', 'Enviado'), ('en_transito', 'En Tránsito'), ('recibido', 'Recibido por Comprador'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Pedido'),
        ),
    ]
